In [19]:
#1

np1=np.array([1,2,3,4,5])
np_min=np.min(np1)
print("Min:",np_min)
np_max=np.max(np1)
print("Max:",np_max)
np_sum=np.sum(np1)
print("Sum:",np_sum)
np_mean=np.mean(np1)
print("Mean:",np_mean)
np_std=np.std(np1)
print("Std:",np_std)

Min: 1
Max: 5
Sum: 15
Mean: 3.0
Std: 1.4142135623730951

In [22]:
#2

def normalise(data):
    mean = np.mean(data, axis=0)
    std = np.std(data, axis=0)
    normalized_data = (data - mean) / std
    return normalized_data

health_data = np.array([[160, 70, 30],   # height, weight, age for individual 1
                        [165, 65, 35],   # height, weight, age for individual 2
                        [170, 75, 40]])  # height, weight, age for individual 3

normalized_data = normalise(health_data)
print(normalized_data)

[[-1.22474487  0.         -1.22474487]
 [ 0.         -1.22474487  0.        ]
 [ 1.22474487  1.22474487  1.22474487]]

In [42]:
#3
scores = np.array([[20, 200, 150], [30, -1, 40], [25, 100, -1]])
averages = []
for i in scores.T:
    average = np.mean(i[i != -1])
    averages.append(average)
print(averages)

[25.0, 150.0, 95.0]

In [26]:
#4


a=np.arange(15,25,0.5)
print(a)

[15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5 20.  20.5 21.  21.5
 22.  22.5 23.  23.5 24.  24.5]

In [41]:
#5
import pandas as pd
import numpy as np
daily_closing_prices = np.array([100, 102, 98, 105, 107, 110, 108, 112, 115, 118, 120])
window_size = 5

df = pd.DataFrame(daily_closing_prices)

df['Moving_avg'] = df.rolling(window=5).mean()
print(df)

      0  Moving_avg
0   100         NaN
1   102         NaN
2    98         NaN
3   105         NaN
4   107       102.4
5   110       104.4
6   108       105.6
7   112       108.4
8   115       110.4
9   118       112.6
10  120       114.6

In [90]:
#6
np1 = np.array([0, 0])
print(np1)

np1 = np.array([[1, 0.5], [0.5, 2]])
print(np2)

[0 0]

TypeError: Field elements must be 2- or 3-tuples, got '0.5'

In [61]:
#7
import numpy as np
np1 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

np2=np.transpose(np1)
print(np2)

[[1 4 7]
 [2 5 8]
 [3 6 9]]

In [69]:
#8
np1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np1,"\n")
c = np1[:, 0] > 5

print(c)

r = np1[c]
print(r)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[False False  True]
[[7 8 9]]

In [50]:
#9
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace'],
        'Age': [25, 30, 35, 40, 45, 50, 55],
        'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Miami', 'Boston'],
        'Department': ['HR', 'IT', 'Finance', 'Marketing', 'Sales', 'IT', 'HR']}

df = pd.DataFrame(data)
df = df[['Name', 'City']] [(df['Age'] < 45) & (df['Department'] != 'HR')]
print(df)

      Name         City
1      Bob  Los Angeles
2  Charlie      Chicago
3    David      Houston

In [58]:
#10
data = {'Department': ['Electronics', 'Electronics', 'Clothing', 'Clothing', 'Home Goods'],
        'Salesperson': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'Sales': [70000, 50000, 30000, 40000, 60000]}
df = pd.DataFrame(data)
avg_s = df.groupby(['Department', 'Salesperson'])['Sales'].mean().reset_index()
print(avg_s,"\n")
avg_d = avg_s.groupby('Department')['Sales'].mean().reset_index()
print(avg_d,"\n")
r = avg_d.sort_values(by='Sales', ascending=False)
print(r)

    Department Salesperson    Sales
0     Clothing     Charlie  30000.0
1     Clothing       David  40000.0
2  Electronics       Alice  70000.0
3  Electronics         Bob  50000.0
4   Home Goods         Eve  60000.0

    Department    Sales
0     Clothing  35000.0
1  Electronics  60000.0
2   Home Goods  60000.0

    Department    Sales
1  Electronics  60000.0
2   Home Goods  60000.0
0     Clothing  35000.0

In [59]:
#11

data = {
    'Product': ['Apples', 'Bananas', 'Cherries', 'Dates', 'Elderberries', 'Flour', 'Grapes'],
    'Category': ['Fruit', 'Fruit', 'Fruit', 'Fruit', 'Fruit', 'Bakery', 'Fruit'],
    'Price': [1.20, 0.50, 3.00, 2.50, 4.00, 1.50, 2.00],
    'Promotion': [True, False, True, True, False, True, False]
}

df = pd.DataFrame(data)
filtered_df = df[(df['Category'] == 'Fruit') & (df['Promotion'] == False) & (df['Price'] > df[df['Category'] == 'Fruit']['Price'].mean())]

print(filtered_df)

        Product Category  Price  Promotion
4  Elderberries    Fruit    4.0      False

In [72]:
#12
employee_data = {
    'Employee': ['Alice', 'Bob', 'Charlie', 'David'],
    'Department': ['HR', 'IT', 'Finance', 'IT'],
    'Manager': ['John', 'Rachel', 'Emily', 'Rachel']
}

# Dataset of employee project assignments
project_data = {
    'Employee': ['Alice', 'Charlie', 'Eve'],
    'Project': ['P1', 'P3', 'P2']
}


project_data = pd.DataFrame(employee_data)
employee_data =  pd.DataFrame(project_data)
merged = employee_data.merge(project_data, on='Employee' ,how='inner')
merged.fillna('Not assigned', inplace=True)
print(merged)

  Employee Department_x Manager_x Department_y Manager_y
0    Alice           HR      John           HR      John
1      Bob           IT    Rachel           IT    Rachel
2  Charlie      Finance     Emily      Finance     Emily
3    David           IT    Rachel           IT    Rachel

In [88]:
#13

df = pd.read_csv("/content/Q13_sports_team_stats.csv")

def win_ratio(data):
  return data

def avg_scr(data):

  n=11
  a=data/n
  return a

def player_per(data):
  if data > 7:
    return 'High'
  elif data > 4:
    return 'Medium'
  else:
    return 'Low'


df['win_r'] = df['Wins'].apply(win_ratio)
df['avg_scr'] = df['Wins'].apply(avg_scr)
df['player_per'] = df['Wins'].apply(player_per)
df

   TeamID  GamesPlayed  Wins  win_r   avg_scr player_per
0       1           10     7      7  0.636364     Medium
1       2           10     6      6  0.545455     Medium
2       3           10     8      8  0.727273       High
3       4           10     5      5  0.454545     Medium
4       5           10     9      9  0.818182       High
5       6           10     6      6  0.545455     Medium
6       7           10     7      7  0.636364     Medium
7       8           10     4      4  0.363636        Low
8       9           10     9      9  0.818182       High
9      10           10     5      5  0.454545     Medium

In [77]:
#14

df = pd.read_csv("/content/Q14_customer_purchases.csv")


df.groupby('LoyaltyProgramSignUp')['PurchaseAmount'].mean()

df

   CustomerID        Date  PurchaseAmount LoyaltyProgramSignUp
0           1  2021-01-31             200           2021-03-01
1           2  2021-02-28             150           2021-03-01
2           3  2021-03-31             300           2021-03-01
3           4  2021-04-30             250           2021-03-01
4           5  2021-05-31             500           2021-03-01
5           6  2021-06-30             350           2021-03-01
6           7  2021-07-31             400           2021-03-01
7           8  2021-08-31             450           2021-03-01
8           9  2021-09-30             550           2021-03-01
9          10  2021-10-31             600           2021-03-01

In [75]:
#15

df = pd.read_csv("/content/Q15_student_grades.csv")
ans = df.groupby(['Subject'])['Grade'].sum().reset_index()
ans = ans.sort_values(by = 'Grade', ascending=True)
print("The education support is needed in\n ",ans.head(2))

The education support is needed in
     Subject  Grade
0  History    251
2  Science    273